### PR TITLE
Configure news

### PR DESCRIPTION
**Pull request by kalinchernev**
Please create a few translated news in Drupal when taking settings. Gatsby site won't be able to build if missing content.

Summary of changes:

- enables a pathauto pattern, `/news/news-title`, this way, there could be a `/news` section and `news/news-page` page.
- enables content translation on the content type
- configures jsonapi endpoint to be `api/news` rather than

### CODE REVIEW

**Comment by haringsrob** [comment]
Hi @kalinchernev,

I only review the gatsby part as the Drupal site will have to be transferred on top of a openeuropa instance at some point anyway.

Setup went fine, however found the following issues:
- Heading "Latest news" is missing.
- On the /news page the content paragraph needs a "ecl-u-type-paragraph" to get the font as in the mockup.
- The news "source" is not yet available. Maybe we should add this in the Drupal site as well to have the full json spec. (I will make the field)
- As far as I know, we do not have news detail pages. But maybe we should verify with Wesley?

One more thing:
- I cannot visit the site without a language suffix. Im not sure if we either need a language switcher or a default path (redirect). But this might be out of scope for now.

**Comment by haringsrob** [comment]
There is no page title yet.
Menu active state is missing.

**Comment by kalinchernev** [comment]
@haringsrob thank you for the review!

The pull request is mainly about configuring a content type in Drupal in order to have news content in gatsby site. That's why I've focused the summary points on the Drupal part. I've also updated the gatsby part of the project to make it easier to understand and see the content, but this part is not ready yet, I know.

Answering your questions:

> Setup went fine, however found the following issues:
> 
> Heading "Latest news" is missing.

I'll surely add that later. There several other elements missing too.
> On the /news page the content paragraph needs a "ecl-u-type-paragraph" to get the font as in the mockup.

Will check that on later stage, thanks for noticing.
> The news "source" is not yet available. Maybe we should add this in the Drupal site as well to have the full json spec. (I will make the field)

Yes please, please add missing fields.
> As far as I know, we do not have news detail pages. But maybe we should verify with Wesley?
> One more thing:
> 
> I cannot visit the site without a language suffix. Im not sure if we either need a language switcher or a default path (redirect). But this might be out of scope for now.

There was a landing page with languages before, but I removed it because the mockup doesn't have one. I also don't know what is best here too, but will investigate and make this part on a later stage.

> There is no page title yet.
> Menu active state is missing.

Not in scope, but have in mind to make, yes.

**Comment by haringsrob** [comment]
I added the heading and the source.

Removed the link, but left the anchors as the mock has links (and is approved) I expect them to ask about it.

**Pull request merged**
